### ISSUE TITLE
feature request: automatic tag creation

### ISSUE THREAD

**Issue by johanatan** [braidchat/braid#1]
Would it be a good idea to allow for automatic tag creation when a never-before-seen tag is utilized in a conversation? [I think it would be nice to save a step but then there is the problem with typos--i.e., inadvertently creating a new tag when attempting to reference an existing one].

Maybe a better solution altogether is to not allow free-form tags but rather display a list of existing tags when the '#' char is typed (and an empty slot at the bottom or top of the list to add a new one on-the-fly).

**Comment by jamesnvc** [comment]
The one thing that I think we'd need to figure out for that interface is to which organization the tag gets added; currently, a user can be in many organizations, each with their own distinct set of tags.  This is definitely something we'd like to do though.

**Comment by johanatan** [comment]
Maybe each 'start a conversation' card would have a combobox/drop-down on it to select the organization?

**Comment by jamesnvc** [comment]
That is possible, although currently it is possible to have tags from multiple organizations in a single conversation.  I would be open to removing that ability though, as it seems more likely to be confusing than useful.

**Comment by rafd** [comment]
I am definitely for having the ability to add a tag via the autocomplete.

Re: typos -- eventually will have a way to edit the name of a tag.
Re: groups/orgs -- for now, could have the autocomplete show a version of the tag for each group for the user to select. If need be, can improve later.

**Comment by rafd** [comment]
Addressed by: https://github.com/braidchat/braid/commit/25656432a93de8f0b8a2a2dcb07816e4df4f47b1
