### ISSUE TITLE
Don't close thread on ESC keypress if there is an unsent draft

### ISSUE THREAD

**Issue by braid-sync** [braidchat/braid#132]
A task for new Braid contributors.

Goal:
Currently, hitting the ESC key while a thread is selected, closes/archives the thread. However... this can be really bad if the user is still typing a message (ie. has text in the composer). Change the existing ESC logic to not close the thread if there is content in the composer.

Notes:
- `braid.core.client.ui.views.new-message` and `braid.core.client.ui.views.thread` are likely relevant namespaces

**Comment by jamesnvc** [comment]
It is worth noting that "really bad" is more of an annoyance, because the typed text will still be saved, so the user can go to the "recent threads" view to get what they where writing back. That being said, it is very annoying and I accidentally do it a lot :stuck_out_tongue:
