### ISSUE TITLE
Show how long the user has been a member on user hover cards

### ISSUE THREAD

**Issue by braid-sync** [braidchat/braid#137]
A task for new Braid contributors.

Goal:
On user-hover-cards (cards that show up when hovering over a user mention), show how long the user has been a member.

Notes:
- the server will need to include this info in the exist user data that it sends to the client (we'll leave it to you to figure where that is)
 - we currently don't explicitly store a timestamp for when a user joins a group, but, it can be figured out by getting the `:db/txInstant` of when the `:group/user` datom was created. Some example code:
```
(d/q
 '[:find [?inst ...]
 :in $ ?user-id ?group-id
 :where
 [?u :user/id ?user-id]
 [?g :group/id ?group-id]
 [?g :group/user ?t ?tx false]
 [?tx :db/txInstant ?inst]]
 (d/history (db/db))
 some-user-id
 some-group-id)
```

**Comment by jamesnvc** [comment]
Closed by #207
