### ISSUE TITLE
Show date dividers in threads

### ISSUE THREAD

**Issue by braid-sync** [braidchat/braid#142]
A task for new Braid contributors.

Goal:
In a thread, show headers between messages at the start of a new day. 
ie.
```
message
message
—— Jan 25 ——
message
```

Notes:
- this can all be done client-side
- you should be able to rely on the user's browser to figure out when a new day starts
- you'll probably need to change `braid.core.client.ui.views.thread/messages-view`
- Braid already includes https://github.com/andrewmcveigh/cljs-time `cljs-time.coerce/from-date` will probably be useful (and other functions)

**Comment by PiotrKurnik** [comment]
Can be closed
