### ISSUE TITLE
Latest changes to the Braid system start appear to cause issues for Emacs/Cider dev environment.

### ISSUE THREAD

**Issue by eipplusone** [braidchat/braid#145]
With the latest changes to the Braid system start, I can no longer reliably start it within Emacs/Cider.

Firstly, figwheel fails to compile cljs:

```Compiling build :desktop-dev to "resources/public/js/dev/desktop.js" from ["src/braid" "src/retouch"]...
Failed to compile build :desktop-dev from ["src/braid" "src/retouch"] in 2.911 seconds.
----  Could not Analyze  target/classes/braid/core/modules_dummy.cljs  ----

  Could not locate braid/core/module_helpers__init.class or braid/core/module_helpers.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.

----  Analysis Error : Please see target/classes/braid/core/modules_dummy.cljs  ----
```

I'm unable to find that file or the `gen-module-requires` macro anywhere in the project.

Could it be that the module_helpers.cljs was forgotten on master?

Secondly, the change has an unfortunate effect of working against how Cider like to have the repls started. When I run `cider-jack-in-clojurescript` it starts `lein repl` and `lein figwheel` separately with `piggieback` and other dependencies injected that are compatible with other nrepl middleware(`nrepl-refactor` for example).

Cider provides `cider-clojurescript-connect` function, but I would need to add the right dependencies in the project itself.

Was it done to simplify the setup process in IDEs like Cursive? I understand that not everyone is using Emacs; the docs here https://github.com/braidchat/braid/blob/master/docs/dev/getting-up-and-running-in-development.md do need to be updated though(the Emacs portion).

**Comment by rafd** [comment]
The figwheel compile issue may be stale files. Try nuking target and the js files. 'rm -rf target' and 'rm -rf resources/public/js'

To not start figwheel via the start! function, you can create a new helper function 'start-without-figwheel' that works similarly to the one in braid.core

Not at computer right now so can't test.

**Comment by eipplusone** [comment]
Well it seems like this is more of an issue pertaining to my environment than to the actual project, so i'm going to close this.
