### ISSUE TITLE
fix frequent "disconnects"

### ISSUE THREAD

**Issue by braid-sync** [braidchat/braid#152]

**Comment by braid-sync** [comment]
➤ Rafal Dittwald commented:

I suspect it has something to do with a long running transaction;
implementing [add multiple states to messages (sending, waiting, error, sent, new, seen)](https://app.asana.com/0/0/200333634258032) would alleviate the issue

**Comment by jamesnvc** [comment]
Seeing this still, in conjunction with extremely high CPU usage, right after a new user joined...there's also a group that seems to have some sort of corrupted state (see #194) which is maybe a causal factor.

**Comment by jamesnvc** [comment]
Observation: CPU spikes on the server right after a message is sent but if the thread the message is in doesn't have any tags, only @-mentioned users, it seems okay. Issue calculating message visibility based on tags?
