### ISSUE TITLE
Check this out!

### ISSUE THREAD

**Issue by Arjuna144** [braidchat/braid#95]
Here is a video http://bit.ly/2qdc06N
Maybe there is inspiration in there

**Comment by Arjuna144** [comment]
Sorry here is the working link: http://bit.ly/2pXeseZ

**Comment by rafd** [comment]
Thanks for sharing @Arjuna144 . The motivations behind we-hate-interruptions are the same as ours and the solution is similar as well (threaded conversations, although their UI is different).

@sjuraschka check out the video. I quite like the way he explains things.

**Comment by braid-sync** [comment]
Sam commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bf649e59-0375-404b-9143-95459966024b):
Yeah that is a good idea to have a longer explanation video he does a great job demoing and explaining each of the features
